// Folgender Code wirft einen ReferenceError
try {
  meineLieblingsFunktion();
} catch (err) {
  console.log("Fehler: " + err);
}
